name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: cd my-blog && npm install
    
    - name: Type check
      run: cd my-blog && npm run type-check
    
    - name: Lint
      run: cd my-blog && npm run lint
    
    - name: Build
      run: cd my-blog && npm run build 